/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  ListPlansApiPlannerGetParams,
  PlanCreate,
  PlanListRead,
  PlanRead,
  PlanUpdate
} from '../../model';

import { customInstance } from '../../client';



  export const getPlanner = () => {
/**
 * Create a new walking plan with OSRM-optimised route.
 * @summary Create Plan
 */
const createPlanApiPlannerPost = (
    planCreate: PlanCreate,
 ) => {
      return customInstance<PlanRead>(
      {url: `/api/planner/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: planCreate
    },
      );
    }
  /**
 * List the current user's plans.
 * @summary List Plans
 */
const listPlansApiPlannerGet = (
    params?: ListPlansApiPlannerGetParams,
 ) => {
      return customInstance<PlanListRead[]>(
      {url: `/api/planner/`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get a single plan with full route details.
 * @summary Get Plan
 */
const getPlanApiPlannerPlanIdGet = (
    planId: string,
 ) => {
      return customInstance<PlanRead>(
      {url: `/api/planner/${planId}`, method: 'GET'
    },
      );
    }
  /**
 * Update a plan's details (e.g. name).
 * @summary Update Plan
 */
const updatePlanApiPlannerPlanIdPatch = (
    planId: string,
    planUpdate: PlanUpdate,
 ) => {
      return customInstance<PlanRead>(
      {url: `/api/planner/${planId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: planUpdate
    },
      );
    }
  /**
 * Delete a plan.
 * @summary Delete Plan
 */
const deletePlanApiPlannerPlanIdDelete = (
    planId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/planner/${planId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Mark a plan as in-progress.
 * @summary Start Plan
 */
const startPlanApiPlannerPlanIdStartPatch = (
    planId: string,
 ) => {
      return customInstance<PlanRead>(
      {url: `/api/planner/${planId}/start`, method: 'PATCH'
    },
      );
    }
  /**
 * Mark a plan as completed.
 * @summary Complete Plan
 */
const completePlanApiPlannerPlanIdCompletePatch = (
    planId: string,
 ) => {
      return customInstance<PlanRead>(
      {url: `/api/planner/${planId}/complete`, method: 'PATCH'
    },
      );
    }
  /**
 * Export a plan as a downloadable GPX file.
 * @summary Export Gpx
 */
const exportGpxApiPlannerPlanIdExportGpxGet = (
    planId: string,
 ) => {
      return customInstance<unknown>(
      {url: `/api/planner/${planId}/export.gpx`, method: 'GET'
    },
      );
    }
  return {createPlanApiPlannerPost,listPlansApiPlannerGet,getPlanApiPlannerPlanIdGet,updatePlanApiPlannerPlanIdPatch,deletePlanApiPlannerPlanIdDelete,startPlanApiPlannerPlanIdStartPatch,completePlanApiPlannerPlanIdCompletePatch,exportGpxApiPlannerPlanIdExportGpxGet}};
export type CreatePlanApiPlannerPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['createPlanApiPlannerPost']>>>
export type ListPlansApiPlannerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['listPlansApiPlannerGet']>>>
export type GetPlanApiPlannerPlanIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['getPlanApiPlannerPlanIdGet']>>>
export type UpdatePlanApiPlannerPlanIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['updatePlanApiPlannerPlanIdPatch']>>>
export type DeletePlanApiPlannerPlanIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['deletePlanApiPlannerPlanIdDelete']>>>
export type StartPlanApiPlannerPlanIdStartPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['startPlanApiPlannerPlanIdStartPatch']>>>
export type CompletePlanApiPlannerPlanIdCompletePatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['completePlanApiPlannerPlanIdCompletePatch']>>>
export type ExportGpxApiPlannerPlanIdExportGpxGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanner>['exportGpxApiPlannerPlanIdExportGpxGet']>>>
