/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  BodyUploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost,
  RaffleCreate,
  RafflePrizeCreate,
  RafflePrizeImageRead,
  RafflePrizeRead,
  RafflePrizeUpdate,
  RaffleRead,
  RaffleUpdate,
  RaffleWinnerContact
} from '../../model';

import { customInstance } from '../../client';



  export const getRaffles = () => {
/**
 * List all raffles. Public.
 * @summary List Raffles
 */
const listRafflesApiRafflesGet = (
    
 ) => {
      return customInstance<RaffleRead[]>(
      {url: `/api/raffles/`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Raffle
 */
const createRaffleApiRafflesPost = (
    raffleCreate: RaffleCreate,
 ) => {
      return customInstance<RaffleRead>(
      {url: `/api/raffles/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: raffleCreate
    },
      );
    }
  /**
 * Get a raffle by id. Public.
 * @summary Get Raffle
 */
const getRaffleApiRafflesRaffleIdGet = (
    raffleId: string,
 ) => {
      return customInstance<RaffleRead>(
      {url: `/api/raffles/${raffleId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Update Raffle
 */
const updateRaffleApiRafflesRaffleIdPatch = (
    raffleId: string,
    raffleUpdate: RaffleUpdate,
 ) => {
      return customInstance<RaffleRead>(
      {url: `/api/raffles/${raffleId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: raffleUpdate
    },
      );
    }
  /**
 * @summary Delete Raffle
 */
const deleteRaffleApiRafflesRaffleIdDelete = (
    raffleId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/raffles/${raffleId}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Add Prize
 */
const addPrizeApiRafflesRaffleIdPrizesPost = (
    raffleId: string,
    rafflePrizeCreate: RafflePrizeCreate,
 ) => {
      return customInstance<RafflePrizeRead>(
      {url: `/api/raffles/${raffleId}/prizes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rafflePrizeCreate
    },
      );
    }
  /**
 * @summary Update Prize
 */
const updatePrizeApiRafflesRaffleIdPrizesPrizeIdPatch = (
    raffleId: string,
    prizeId: string,
    rafflePrizeUpdate: RafflePrizeUpdate,
 ) => {
      return customInstance<RafflePrizeRead>(
      {url: `/api/raffles/${raffleId}/prizes/${prizeId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: rafflePrizeUpdate
    },
      );
    }
  /**
 * @summary Delete Prize
 */
const deletePrizeApiRafflesRaffleIdPrizesPrizeIdDelete = (
    raffleId: string,
    prizeId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/raffles/${raffleId}/prizes/${prizeId}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Upload Prize Image
 */
const uploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost = (
    raffleId: string,
    prizeId: string,
    bodyUploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost: BodyUploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost.file);

      return customInstance<RafflePrizeImageRead>(
      {url: `/api/raffles/${raffleId}/prizes/${prizeId}/images`, method: 'POST',
       data: formData
    },
      );
    }
  /**
 * @summary Delete Prize Image
 */
const deletePrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesImageIdDelete = (
    raffleId: string,
    prizeId: string,
    imageId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/raffles/${raffleId}/prizes/${prizeId}/images/${imageId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Serve a raffle prize image by filename. Public.
 * @summary Serve Prize Image
 */
const servePrizeImageApiRafflesImagesFilenameGet = (
    filename: string,
 ) => {
      return customInstance<unknown>(
      {url: `/api/raffles/images/${filename}`, method: 'GET'
    },
      );
    }
  /**
 * Draw winners for the raffle. One random user per prize, no duplicates.

Eligible pool: verified users with user_type in (volunteer, moderator) — i.e.
everyone except admins/superusers.
 * @summary Draw Raffle
 */
const drawRaffleApiRafflesRaffleIdDrawPost = (
    raffleId: string,
 ) => {
      return customInstance<RaffleRead>(
      {url: `/api/raffles/${raffleId}/draw`, method: 'POST'
    },
      );
    }
  /**
 * Admin-only winner contact details for a drawn raffle.
 * @summary List Winner Contacts
 */
const listWinnerContactsApiRafflesRaffleIdWinnersGet = (
    raffleId: string,
 ) => {
      return customInstance<RaffleWinnerContact[]>(
      {url: `/api/raffles/${raffleId}/winners`, method: 'GET'
    },
      );
    }
  /**
 * Pick a fresh winner for a single prize (e.g. when the original winner
isn't responding). Excludes anyone already holding a prize in this raffle —
including the prize's current winner — so they cannot be re-picked.
 * @summary Redraw Prize
 */
const redrawPrizeApiRafflesRaffleIdPrizesPrizeIdRedrawPost = (
    raffleId: string,
    prizeId: string,
 ) => {
      return customInstance<RafflePrizeRead>(
      {url: `/api/raffles/${raffleId}/prizes/${prizeId}/redraw`, method: 'POST'
    },
      );
    }
  return {listRafflesApiRafflesGet,createRaffleApiRafflesPost,getRaffleApiRafflesRaffleIdGet,updateRaffleApiRafflesRaffleIdPatch,deleteRaffleApiRafflesRaffleIdDelete,addPrizeApiRafflesRaffleIdPrizesPost,updatePrizeApiRafflesRaffleIdPrizesPrizeIdPatch,deletePrizeApiRafflesRaffleIdPrizesPrizeIdDelete,uploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost,deletePrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesImageIdDelete,servePrizeImageApiRafflesImagesFilenameGet,drawRaffleApiRafflesRaffleIdDrawPost,listWinnerContactsApiRafflesRaffleIdWinnersGet,redrawPrizeApiRafflesRaffleIdPrizesPrizeIdRedrawPost}};
export type ListRafflesApiRafflesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['listRafflesApiRafflesGet']>>>
export type CreateRaffleApiRafflesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['createRaffleApiRafflesPost']>>>
export type GetRaffleApiRafflesRaffleIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['getRaffleApiRafflesRaffleIdGet']>>>
export type UpdateRaffleApiRafflesRaffleIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['updateRaffleApiRafflesRaffleIdPatch']>>>
export type DeleteRaffleApiRafflesRaffleIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['deleteRaffleApiRafflesRaffleIdDelete']>>>
export type AddPrizeApiRafflesRaffleIdPrizesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['addPrizeApiRafflesRaffleIdPrizesPost']>>>
export type UpdatePrizeApiRafflesRaffleIdPrizesPrizeIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['updatePrizeApiRafflesRaffleIdPrizesPrizeIdPatch']>>>
export type DeletePrizeApiRafflesRaffleIdPrizesPrizeIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['deletePrizeApiRafflesRaffleIdPrizesPrizeIdDelete']>>>
export type UploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['uploadPrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesPost']>>>
export type DeletePrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesImageIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['deletePrizeImageApiRafflesRaffleIdPrizesPrizeIdImagesImageIdDelete']>>>
export type ServePrizeImageApiRafflesImagesFilenameGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['servePrizeImageApiRafflesImagesFilenameGet']>>>
export type DrawRaffleApiRafflesRaffleIdDrawPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['drawRaffleApiRafflesRaffleIdDrawPost']>>>
export type ListWinnerContactsApiRafflesRaffleIdWinnersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['listWinnerContactsApiRafflesRaffleIdWinnersGet']>>>
export type RedrawPrizeApiRafflesRaffleIdPrizesPrizeIdRedrawPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRaffles>['redrawPrizeApiRafflesRaffleIdPrizesPrizeIdRedrawPost']>>>
