/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import type {
  ForgotPassword,
  ResetPassword,
  Token,
  UserCreate,
  UserLogin,
  UserRead,
  UserUpdateType
} from '../../model';

import { customInstance } from '../../client';



  export const getAuth = () => {
/**
 * List all users. Requires admin access.
 * @summary List Users
 */
const listUsersApiAuthUsersGet = (
    
 ) => {
      return customInstance<UserRead[]>(
      {url: `/api/auth/users`, method: 'GET'
    },
      );
    }
  /**
 * @summary Register
 */
const registerApiAuthRegisterPost = (
    userCreate: UserCreate,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate
    },
      );
    }
  /**
 * @summary Login
 */
const loginApiAuthLoginPost = (
    userLogin: UserLogin,
 ) => {
      return customInstance<Token>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLogin
    },
      );
    }
  /**
 * @summary Update User Type
 */
const updateUserTypeApiAuthUsersUserIdTypePatch = (
    userId: number,
    userUpdateType: UserUpdateType,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/users/${userId}/type`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateType
    },
      );
    }
  /**
 * @summary Delete User
 */
const deleteUserApiAuthUsersUserIdDelete = (
    userId: number,
 ) => {
      return customInstance<void>(
      {url: `/api/auth/users/${userId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Generate a password reset token for the given email.
 * @summary Forgot Password
 */
const forgotPasswordApiAuthForgotPasswordPost = (
    forgotPassword: ForgotPassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPassword
    },
      );
    }
  /**
 * Reset a user's password using a valid reset token.
 * @summary Reset Password
 */
const resetPasswordApiAuthResetPasswordPost = (
    resetPassword: ResetPassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPassword
    },
      );
    }
  return {listUsersApiAuthUsersGet,registerApiAuthRegisterPost,loginApiAuthLoginPost,updateUserTypeApiAuthUsersUserIdTypePatch,deleteUserApiAuthUsersUserIdDelete,forgotPasswordApiAuthForgotPasswordPost,resetPasswordApiAuthResetPasswordPost}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ListUsersApiAuthUsersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['listUsersApiAuthUsersGet']>>>
export type RegisterApiAuthRegisterPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['registerApiAuthRegisterPost']>>>
export type LoginApiAuthLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['loginApiAuthLoginPost']>>>
export type UpdateUserTypeApiAuthUsersUserIdTypePatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['updateUserTypeApiAuthUsersUserIdTypePatch']>>>
export type DeleteUserApiAuthUsersUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['deleteUserApiAuthUsersUserIdDelete']>>>
export type ForgotPasswordApiAuthForgotPasswordPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['forgotPasswordApiAuthForgotPasswordPost']>>>
export type ResetPasswordApiAuthResetPasswordPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['resetPasswordApiAuthResetPasswordPost']>>>
