/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getAuth = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Register
 */
const registerApiAuthRegisterPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/auth/register`,undefined,options
    );
  }
/**
 * @summary Login
 */
const loginApiAuthLoginPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/auth/login`,undefined,options
    );
  }
return {registerApiAuthRegisterPost,loginApiAuthLoginPost}};
export type RegisterApiAuthRegisterPostResult = AxiosResponse<unknown>
export type LoginApiAuthLoginPostResult = AxiosResponse<unknown>
