/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  BodyUploadAvatarApiAuthMeAvatarPut,
  ChangePassword,
  ForgotPassword,
  ProfileUpdate,
  RefreshRequest,
  ResetPassword,
  SocialLoginRequest,
  Token,
  UserCreate,
  UserLogin,
  UserRead,
  UserUpdateType,
  VerifyEmailApiAuthVerifyGetParams
} from '../../model';

import { customInstance } from '../../client';



  export const getAuth = () => {
/**
 * Return the current user's profile.
 * @summary Get Profile
 */
const getProfileApiAuthMeGet = (
    
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  /**
 * Delete current user profile
 * @summary Delete Profile
 */
const deleteProfileApiAuthMeDelete = (
    
 ) => {
      return customInstance<void>(
      {url: `/api/auth/me`, method: 'DELETE'
    },
      );
    }
  /**
 * Update the current user's profile (name, avatar_url).
 * @summary Update Profile
 */
const updateProfileApiAuthMePatch = (
    profileUpdate: ProfileUpdate,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: profileUpdate
    },
      );
    }
  /**
 * Upload a custom avatar image. Resized to 300x300 max.
 * @summary Upload Avatar
 */
const uploadAvatarApiAuthMeAvatarPut = (
    bodyUploadAvatarApiAuthMeAvatarPut: BodyUploadAvatarApiAuthMeAvatarPut,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadAvatarApiAuthMeAvatarPut.file);

      return customInstance<UserRead>(
      {url: `/api/auth/me/avatar`, method: 'PUT',
       data: formData
    },
      );
    }
  /**
 * Change the current user's password. Requires current password.
 * @summary Change Password
 */
const changePasswordApiAuthMePasswordPatch = (
    changePassword: ChangePassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePassword
    },
      );
    }
  /**
 * List all users. Requires admin access.
 * @summary List Users
 */
const listUsersApiAuthUsersGet = (
    
 ) => {
      return customInstance<UserRead[]>(
      {url: `/api/auth/users`, method: 'GET'
    },
      );
    }
  /**
 * @summary Register
 */
const registerApiAuthRegisterPost = (
    userCreate: UserCreate,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate
    },
      );
    }
  /**
 * Verify a user's email address using the token from the verification email.
 * @summary Verify Email
 */
const verifyEmailApiAuthVerifyGet = (
    params: VerifyEmailApiAuthVerifyGetParams,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/verify`, method: 'GET',
        params
    },
      );
    }
  /**
 * Resend the verification email. Uses ForgotPassword schema (just an email field).
 * @summary Resend Verification
 */
const resendVerificationApiAuthResendVerificationPost = (
    forgotPassword: ForgotPassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/resend-verification`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPassword
    },
      );
    }
  /**
 * @summary Login
 */
const loginApiAuthLoginPost = (
    userLogin: UserLogin,
 ) => {
      return customInstance<Token>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLogin
    },
      );
    }
  /**
 * Exchange a valid refresh token for a new access token + refresh token (rotation).
 * @summary Refresh Token
 */
const refreshTokenApiAuthRefreshPost = (
    refreshRequest: RefreshRequest,
 ) => {
      return customInstance<Token>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  /**
 * Sign in (or sign up) using a verified social provider credential.
 * @summary Social Login
 */
const socialLoginApiAuthProviderLoginPost = (
    provider: string,
    socialLoginRequest: SocialLoginRequest,
 ) => {
      return customInstance<Token>(
      {url: `/api/auth/${provider}/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: socialLoginRequest
    },
      );
    }
  /**
 * Attach a provider identity to the currently authenticated user.
 * @summary Link Provider
 */
const linkProviderApiAuthProviderLinkPost = (
    provider: string,
    socialLoginRequest: SocialLoginRequest,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/${provider}/link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: socialLoginRequest
    },
      );
    }
  /**
 * Detach a provider from the current user. Refuses if it would lock them out.
 * @summary Unlink Provider
 */
const unlinkProviderApiAuthProviderLinkDelete = (
    provider: string,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/${provider}/link`, method: 'DELETE'
    },
      );
    }
  /**
 * Revoke a refresh token on logout.
 * @summary Logout
 */
const logoutApiAuthLogoutPost = (
    refreshRequest: RefreshRequest,
 ) => {
      return customInstance<void>(
      {url: `/api/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  /**
 * @summary Update User Type
 */
const updateUserTypeApiAuthUsersUserIdTypePatch = (
    userId: string,
    userUpdateType: UserUpdateType,
 ) => {
      return customInstance<UserRead>(
      {url: `/api/auth/users/${userId}/type`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateType
    },
      );
    }
  /**
 * @summary Delete User
 */
const deleteUserApiAuthUsersUserIdDelete = (
    userId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/auth/users/${userId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Generate a password reset token for the given email.
 * @summary Forgot Password
 */
const forgotPasswordApiAuthForgotPasswordPost = (
    forgotPassword: ForgotPassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPassword
    },
      );
    }
  /**
 * Reset a user's password using a valid reset token.
 * @summary Reset Password
 */
const resetPasswordApiAuthResetPasswordPost = (
    resetPassword: ResetPassword,
 ) => {
      return customInstance<unknown>(
      {url: `/api/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPassword
    },
      );
    }
  return {getProfileApiAuthMeGet,deleteProfileApiAuthMeDelete,updateProfileApiAuthMePatch,uploadAvatarApiAuthMeAvatarPut,changePasswordApiAuthMePasswordPatch,listUsersApiAuthUsersGet,registerApiAuthRegisterPost,verifyEmailApiAuthVerifyGet,resendVerificationApiAuthResendVerificationPost,loginApiAuthLoginPost,refreshTokenApiAuthRefreshPost,socialLoginApiAuthProviderLoginPost,linkProviderApiAuthProviderLinkPost,unlinkProviderApiAuthProviderLinkDelete,logoutApiAuthLogoutPost,updateUserTypeApiAuthUsersUserIdTypePatch,deleteUserApiAuthUsersUserIdDelete,forgotPasswordApiAuthForgotPasswordPost,resetPasswordApiAuthResetPasswordPost}};
export type GetProfileApiAuthMeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['getProfileApiAuthMeGet']>>>
export type DeleteProfileApiAuthMeDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['deleteProfileApiAuthMeDelete']>>>
export type UpdateProfileApiAuthMePatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['updateProfileApiAuthMePatch']>>>
export type UploadAvatarApiAuthMeAvatarPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['uploadAvatarApiAuthMeAvatarPut']>>>
export type ChangePasswordApiAuthMePasswordPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['changePasswordApiAuthMePasswordPatch']>>>
export type ListUsersApiAuthUsersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['listUsersApiAuthUsersGet']>>>
export type RegisterApiAuthRegisterPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['registerApiAuthRegisterPost']>>>
export type VerifyEmailApiAuthVerifyGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['verifyEmailApiAuthVerifyGet']>>>
export type ResendVerificationApiAuthResendVerificationPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['resendVerificationApiAuthResendVerificationPost']>>>
export type LoginApiAuthLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['loginApiAuthLoginPost']>>>
export type RefreshTokenApiAuthRefreshPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['refreshTokenApiAuthRefreshPost']>>>
export type SocialLoginApiAuthProviderLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['socialLoginApiAuthProviderLoginPost']>>>
export type LinkProviderApiAuthProviderLinkPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['linkProviderApiAuthProviderLinkPost']>>>
export type UnlinkProviderApiAuthProviderLinkDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['unlinkProviderApiAuthProviderLinkDelete']>>>
export type LogoutApiAuthLogoutPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['logoutApiAuthLogoutPost']>>>
export type UpdateUserTypeApiAuthUsersUserIdTypePatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['updateUserTypeApiAuthUsersUserIdTypePatch']>>>
export type DeleteUserApiAuthUsersUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['deleteUserApiAuthUsersUserIdDelete']>>>
export type ForgotPasswordApiAuthForgotPasswordPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['forgotPasswordApiAuthForgotPasswordPost']>>>
export type ResetPasswordApiAuthResetPasswordPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['resetPasswordApiAuthResetPasswordPost']>>>
