/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  BodyUploadProfileImageApiCommunitiesCommunityIdImagePut,
  CommunityCreate,
  CommunityDetail,
  CommunityLeaderboardApiCommunitiesCommunityIdLeaderboardGetParams,
  CommunityOwnerUpdate,
  CommunityRead,
  CommunityStatusUpdate,
  CommunityVisibilityUpdate,
  DeleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDeleteParams,
  EventCreate,
  EventOccurrenceRead,
  EventUpdate,
  LeaderboardEntry,
  ListCommunitiesApiCommunitiesGetParams,
  ListEventsApiCommunitiesCommunityIdEventsGetParams,
  MembershipAction,
  MembershipRead,
  MyCommunities,
  PostCreate,
  PostRead,
  PostUpdate
} from '../../model';

import { customInstance } from '../../client';



  export const getCommunities = () => {
/**
 * Create a new community. The current user becomes the owner.
 * @summary Create Community
 */
const createCommunityApiCommunitiesPost = (
    communityCreate: CommunityCreate,
 ) => {
      return customInstance<CommunityRead>(
      {url: `/api/communities/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: communityCreate
    },
      );
    }
  /**
 * List communities with optional search and location filters.

Visibility: anon/volunteer see active only. Owner also sees own under_review.
Moderator+ sees all.
 * @summary List Communities
 */
const listCommunitiesApiCommunitiesGet = (
    params?: ListCommunitiesApiCommunitiesGetParams,
 ) => {
      return customInstance<CommunityRead[]>(
      {url: `/api/communities/`, method: 'GET',
        params
    },
      );
    }
  /**
 * Return the current user's owned and joined (approved) communities.
 * @summary My Communities
 */
const myCommunitiesApiCommunitiesMineGet = (
    
 ) => {
      return customInstance<MyCommunities>(
      {url: `/api/communities/mine`, method: 'GET'
    },
      );
    }
  /**
 * Get a single community. Posts and events are only visible to members, owner, or moderator+.
 * @summary Get Community
 */
const getCommunityApiCommunitiesCommunityIdGet = (
    communityId: string,
 ) => {
      return customInstance<CommunityDetail>(
      {url: `/api/communities/${communityId}`, method: 'GET'
    },
      );
    }
  /**
 * Delete a community. Owner, moderator, or admin only.
 * @summary Delete Community
 */
const deleteCommunityApiCommunitiesCommunityIdDelete = (
    communityId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/communities/${communityId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Upload or replace the community profile image. Owner only.
 * @summary Upload Profile Image
 */
const uploadProfileImageApiCommunitiesCommunityIdImagePut = (
    communityId: string,
    bodyUploadProfileImageApiCommunitiesCommunityIdImagePut: BodyUploadProfileImageApiCommunitiesCommunityIdImagePut,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadProfileImageApiCommunitiesCommunityIdImagePut.file);

      return customInstance<CommunityRead>(
      {url: `/api/communities/${communityId}/image`, method: 'PUT',
       data: formData
    },
      );
    }
  /**
 * Set community status to active or under_review. Moderator+ only.
 * @summary Update Community Status
 */
const updateCommunityStatusApiCommunitiesCommunityIdStatusPatch = (
    communityId: string,
    communityStatusUpdate: CommunityStatusUpdate,
 ) => {
      return customInstance<CommunityRead>(
      {url: `/api/communities/${communityId}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: communityStatusUpdate
    },
      );
    }
  /**
 * Toggle community visibility between public and private. Owner only.
 * @summary Update Community Visibility
 */
const updateCommunityVisibilityApiCommunitiesCommunityIdVisibilityPatch = (
    communityId: string,
    communityVisibilityUpdate: CommunityVisibilityUpdate,
 ) => {
      return customInstance<CommunityRead>(
      {url: `/api/communities/${communityId}/visibility`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: communityVisibilityUpdate
    },
      );
    }
  /**
 * Transfer community ownership. Allowed for the current owner or moderator+.
 * @summary Update Community Owner
 */
const updateCommunityOwnerApiCommunitiesCommunityIdOwnerPatch = (
    communityId: string,
    communityOwnerUpdate: CommunityOwnerUpdate,
 ) => {
      return customInstance<CommunityRead>(
      {url: `/api/communities/${communityId}/owner`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: communityOwnerUpdate
    },
      );
    }
  /**
 * Create a post on a community page. Owner only.
 * @summary Create Post
 */
const createPostApiCommunitiesCommunityIdPostsPost = (
    communityId: string,
    postCreate: PostCreate,
 ) => {
      return customInstance<PostRead>(
      {url: `/api/communities/${communityId}/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postCreate
    },
      );
    }
  /**
 * Edit a post. Owner only.
 * @summary Update Post
 */
const updatePostApiCommunitiesCommunityIdPostsPostIdPatch = (
    communityId: string,
    postId: string,
    postUpdate: PostUpdate,
 ) => {
      return customInstance<PostRead>(
      {url: `/api/communities/${communityId}/posts/${postId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: postUpdate
    },
      );
    }
  /**
 * Delete a post. Owner or moderator+ only.
 * @summary Delete Post
 */
const deletePostApiCommunitiesCommunityIdPostsPostIdDelete = (
    communityId: string,
    postId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/communities/${communityId}/posts/${postId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Create a cleanup event. Owner only.
 * @summary Create Event
 */
const createEventApiCommunitiesCommunityIdEventsPost = (
    communityId: string,
    eventCreate: EventCreate,
 ) => {
      return customInstance<EventOccurrenceRead>(
      {url: `/api/communities/${communityId}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventCreate
    },
      );
    }
  /**
 * List expanded event occurrences for a community within a date range.
 * @summary List Events
 */
const listEventsApiCommunitiesCommunityIdEventsGet = (
    communityId: string,
    params?: ListEventsApiCommunitiesCommunityIdEventsGetParams,
 ) => {
      return customInstance<EventOccurrenceRead[]>(
      {url: `/api/communities/${communityId}/events`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get a single event or occurrence.
 * @summary Get Event
 */
const getEventApiCommunitiesCommunityIdEventsOccurrenceIdGet = (
    communityId: string,
    occurrenceId: string,
 ) => {
      return customInstance<EventOccurrenceRead>(
      {url: `/api/communities/${communityId}/events/${occurrenceId}`, method: 'GET'
    },
      );
    }
  /**
 * Edit an event. Owner only. Supports scoped updates for recurring events.
 * @summary Update Event
 */
const updateEventApiCommunitiesCommunityIdEventsOccurrenceIdPatch = (
    communityId: string,
    occurrenceId: string,
    eventUpdate: EventUpdate,
 ) => {
      return customInstance<EventOccurrenceRead>(
      {url: `/api/communities/${communityId}/events/${occurrenceId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: eventUpdate
    },
      );
    }
  /**
 * Delete an event or occurrence. Owner or moderator+ only.

For recurring events, ``scope`` controls what is deleted:
- ``this``: cancel this single occurrence.
- ``this_and_future``: end the series before this date.
- ``all``: delete the entire series (parent + exceptions).
 * @summary Delete Event
 */
const deleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDelete = (
    communityId: string,
    occurrenceId: string,
    params?: DeleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDeleteParams,
 ) => {
      return customInstance<void>(
      {url: `/api/communities/${communityId}/events/${occurrenceId}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * Mark current user as attending an event. Must be a community member or owner.
 * @summary Attend Event
 */
const attendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendPost = (
    communityId: string,
    occurrenceId: string,
 ) => {
      return customInstance<EventOccurrenceRead>(
      {url: `/api/communities/${communityId}/events/${occurrenceId}/attend`, method: 'POST'
    },
      );
    }
  /**
 * Remove current user's attendance from an event.
 * @summary Unattend Event
 */
const unattendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendDelete = (
    communityId: string,
    occurrenceId: string,
 ) => {
      return customInstance<EventOccurrenceRead>(
      {url: `/api/communities/${communityId}/events/${occurrenceId}/attend`, method: 'DELETE'
    },
      );
    }
  /**
 * Request to join a community. Status starts as pending until owner approves.
 * @summary Join Community
 */
const joinCommunityApiCommunitiesCommunityIdJoinPost = (
    communityId: string,
 ) => {
      return customInstance<MembershipRead>(
      {url: `/api/communities/${communityId}/join`, method: 'POST'
    },
      );
    }
  /**
 * List memberships. Only the community owner, admin, or superuser can access.
 * @summary List Memberships
 */
const listMembershipsApiCommunitiesCommunityIdMembershipsGet = (
    communityId: string,
 ) => {
      return customInstance<MembershipRead[]>(
      {url: `/api/communities/${communityId}/memberships`, method: 'GET'
    },
      );
    }
  /**
 * Approve or reject a membership request. Owner only.
 * @summary Update Membership
 */
const updateMembershipApiCommunitiesCommunityIdMembershipsMembershipIdPatch = (
    communityId: string,
    membershipId: string,
    membershipAction: MembershipAction,
 ) => {
      return customInstance<MembershipRead>(
      {url: `/api/communities/${communityId}/memberships/${membershipId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: membershipAction
    },
      );
    }
  /**
 * Leave a community. Owner cannot leave — they must delete the community.
 * @summary Leave Community
 */
const leaveCommunityApiCommunitiesCommunityIdLeaveDelete = (
    communityId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/communities/${communityId}/leave`, method: 'DELETE'
    },
      );
    }
  /**
 * List approved members of a community. Only the community owner or an admin can access.
 * @summary List Public Members
 */
const listPublicMembersApiCommunitiesCommunityIdMembersGet = (
    communityId: string,
 ) => {
      return customInstance<MembershipRead[]>(
      {url: `/api/communities/${communityId}/members`, method: 'GET'
    },
      );
    }
  /**
 * Return community members ranked by number of reports cleaned globally. Only members and the owner can access.
 * @summary Community Leaderboard
 */
const communityLeaderboardApiCommunitiesCommunityIdLeaderboardGet = (
    communityId: string,
    params?: CommunityLeaderboardApiCommunitiesCommunityIdLeaderboardGetParams,
 ) => {
      return customInstance<LeaderboardEntry[]>(
      {url: `/api/communities/${communityId}/leaderboard`, method: 'GET',
        params
    },
      );
    }
  return {createCommunityApiCommunitiesPost,listCommunitiesApiCommunitiesGet,myCommunitiesApiCommunitiesMineGet,getCommunityApiCommunitiesCommunityIdGet,deleteCommunityApiCommunitiesCommunityIdDelete,uploadProfileImageApiCommunitiesCommunityIdImagePut,updateCommunityStatusApiCommunitiesCommunityIdStatusPatch,updateCommunityVisibilityApiCommunitiesCommunityIdVisibilityPatch,updateCommunityOwnerApiCommunitiesCommunityIdOwnerPatch,createPostApiCommunitiesCommunityIdPostsPost,updatePostApiCommunitiesCommunityIdPostsPostIdPatch,deletePostApiCommunitiesCommunityIdPostsPostIdDelete,createEventApiCommunitiesCommunityIdEventsPost,listEventsApiCommunitiesCommunityIdEventsGet,getEventApiCommunitiesCommunityIdEventsOccurrenceIdGet,updateEventApiCommunitiesCommunityIdEventsOccurrenceIdPatch,deleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDelete,attendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendPost,unattendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendDelete,joinCommunityApiCommunitiesCommunityIdJoinPost,listMembershipsApiCommunitiesCommunityIdMembershipsGet,updateMembershipApiCommunitiesCommunityIdMembershipsMembershipIdPatch,leaveCommunityApiCommunitiesCommunityIdLeaveDelete,listPublicMembersApiCommunitiesCommunityIdMembersGet,communityLeaderboardApiCommunitiesCommunityIdLeaderboardGet}};
export type CreateCommunityApiCommunitiesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['createCommunityApiCommunitiesPost']>>>
export type ListCommunitiesApiCommunitiesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['listCommunitiesApiCommunitiesGet']>>>
export type MyCommunitiesApiCommunitiesMineGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['myCommunitiesApiCommunitiesMineGet']>>>
export type GetCommunityApiCommunitiesCommunityIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['getCommunityApiCommunitiesCommunityIdGet']>>>
export type DeleteCommunityApiCommunitiesCommunityIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['deleteCommunityApiCommunitiesCommunityIdDelete']>>>
export type UploadProfileImageApiCommunitiesCommunityIdImagePutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['uploadProfileImageApiCommunitiesCommunityIdImagePut']>>>
export type UpdateCommunityStatusApiCommunitiesCommunityIdStatusPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updateCommunityStatusApiCommunitiesCommunityIdStatusPatch']>>>
export type UpdateCommunityVisibilityApiCommunitiesCommunityIdVisibilityPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updateCommunityVisibilityApiCommunitiesCommunityIdVisibilityPatch']>>>
export type UpdateCommunityOwnerApiCommunitiesCommunityIdOwnerPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updateCommunityOwnerApiCommunitiesCommunityIdOwnerPatch']>>>
export type CreatePostApiCommunitiesCommunityIdPostsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['createPostApiCommunitiesCommunityIdPostsPost']>>>
export type UpdatePostApiCommunitiesCommunityIdPostsPostIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updatePostApiCommunitiesCommunityIdPostsPostIdPatch']>>>
export type DeletePostApiCommunitiesCommunityIdPostsPostIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['deletePostApiCommunitiesCommunityIdPostsPostIdDelete']>>>
export type CreateEventApiCommunitiesCommunityIdEventsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['createEventApiCommunitiesCommunityIdEventsPost']>>>
export type ListEventsApiCommunitiesCommunityIdEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['listEventsApiCommunitiesCommunityIdEventsGet']>>>
export type GetEventApiCommunitiesCommunityIdEventsOccurrenceIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['getEventApiCommunitiesCommunityIdEventsOccurrenceIdGet']>>>
export type UpdateEventApiCommunitiesCommunityIdEventsOccurrenceIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updateEventApiCommunitiesCommunityIdEventsOccurrenceIdPatch']>>>
export type DeleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['deleteEventApiCommunitiesCommunityIdEventsOccurrenceIdDelete']>>>
export type AttendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['attendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendPost']>>>
export type UnattendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['unattendEventApiCommunitiesCommunityIdEventsOccurrenceIdAttendDelete']>>>
export type JoinCommunityApiCommunitiesCommunityIdJoinPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['joinCommunityApiCommunitiesCommunityIdJoinPost']>>>
export type ListMembershipsApiCommunitiesCommunityIdMembershipsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['listMembershipsApiCommunitiesCommunityIdMembershipsGet']>>>
export type UpdateMembershipApiCommunitiesCommunityIdMembershipsMembershipIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['updateMembershipApiCommunitiesCommunityIdMembershipsMembershipIdPatch']>>>
export type LeaveCommunityApiCommunitiesCommunityIdLeaveDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['leaveCommunityApiCommunitiesCommunityIdLeaveDelete']>>>
export type ListPublicMembersApiCommunitiesCommunityIdMembersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['listPublicMembersApiCommunitiesCommunityIdMembersGet']>>>
export type CommunityLeaderboardApiCommunitiesCommunityIdLeaderboardGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCommunities>['communityLeaderboardApiCommunitiesCommunityIdLeaderboardGet']>>>
