/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getVolunteers = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary List Volunteers
 */
const listVolunteersApiVolunteersGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/api/volunteers/`,options
    );
  }
/**
 * @summary Claim Report
 */
const claimReportApiVolunteersClaimReportIdPost = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/volunteers/claim/${reportId}`,undefined,options
    );
  }
return {listVolunteersApiVolunteersGet,claimReportApiVolunteersClaimReportIdPost}};
export type ListVolunteersApiVolunteersGetResult = AxiosResponse<unknown>
export type ClaimReportApiVolunteersClaimReportIdPostResult = AxiosResponse<unknown>
