/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  BadgeRead
} from '../../model';

import { customInstance } from '../../client';



  export const getBadges = () => {
/**
 * Mark a badge as seen by the current user.

Re-running evaluate_badges first ensures the row exists even if the user
hits this endpoint before their next profile fetch.
 * @summary Acknowledge Badge
 */
const acknowledgeBadgeApiBadgesBadgeIdAcknowledgePost = (
    badgeId: string,
 ) => {
      return customInstance<BadgeRead>(
      {url: `/api/badges/${badgeId}/acknowledge`, method: 'POST'
    },
      );
    }
  return {acknowledgeBadgeApiBadgesBadgeIdAcknowledgePost}};
export type AcknowledgeBadgeApiBadgesBadgeIdAcknowledgePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBadges>['acknowledgeBadgeApiBadgesBadgeIdAcknowledgePost']>>>
