/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import { customInstance } from '../../client';



  export const getAdmin = () => {
/**
 * Scan pending reports and append a `stale` log entry to those inactive for the configured window.
 * @summary Trigger Mark Stale
 */
const triggerMarkStaleApiAdminTasksMarkStalePost = (
    
 ) => {
      return customInstance<unknown>(
      {url: `/api/admin/tasks/mark-stale`, method: 'POST'
    },
      );
    }
  return {triggerMarkStaleApiAdminTasksMarkStalePost}};
export type TriggerMarkStaleApiAdminTasksMarkStalePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['triggerMarkStaleApiAdminTasksMarkStalePost']>>>
