/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface BinRead {
  id: string;
  latitude: number;
  longitude: number;
  description: string;
  address?: string | null;
  created_by_user_id?: string | null;
  created_at: string;
  updated_at?: string | null;
}
