/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface BinUpdate {
  latitude?: number | null;
  longitude?: number | null;
  description?: string | null;
}
