/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface BodyCreateReportApiReportsPost {
  latitude: number;
  longitude: number;
  description?: string;
  what3words?: string | null;
  image?: Blob | null;
}
