/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface CommunityCreate {
  name: string;
  description?: string;
  latitude: number;
  longitude: number;
  radius_km: number;
  facebook_url?: string | null;
  visibility?: string;
}
