/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface CommunityRead {
  id: string;
  name: string;
  description: string;
  facebook_url?: string | null;
  profile_image?: string | null;
  latitude: number;
  longitude: number;
  radius_km: number;
  owner_id: string;
  status: string;
  created_at: string;
}
