/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export type CommunityLeaderboardApiCommunitiesCommunityIdLeaderboardGetParams = {
/**
 * Number of months to look back
 * @minimum 1
 * @maximum 12
 */
months?: number;
/**
 * Number of top members to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
