/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface EventUpdate {
  description?: string | null;
  date?: string | null;
  meeting_latitude?: number | null;
  meeting_longitude?: number | null;
  report_ids?: number[] | null;
}
