/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface EventCreate {
  title: string;
  description?: string | null;
  date: string;
  meeting_latitude: number;
  meeting_longitude: number;
  report_ids?: number[];
}
