/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface LeaderboardEntry {
  user_id: string;
  rank: number;
  name: string;
  cleaned_count: number;
}
