/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export type ListBinsApiBinsGetParams = {
/**
 * Centre latitude for radius query
 */
latitude?: number | null;
/**
 * Centre longitude for radius query
 */
longitude?: number | null;
/**
 * Radius in kilometres
 */
radius_km?: number;
};
