/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */

export type ListReportsApiReportsGetParams = {
status?: string | null;
};
