/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export type ListCommunitiesApiCommunitiesGetParams = {
/**
 * Search by community name
 */
search?: string | null;
/**
 * Latitude for nearby search
 */
lat?: number | null;
/**
 * Longitude for nearby search
 */
lng?: number | null;
/**
 * Radius in km for nearby search
 */
radius_km?: number | null;
};
