/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface MembershipRead {
  id: number;
  community_id: number;
  user_id: number;
  user_name?: string;
  status: string;
  created_at: string;
}
