/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { CommunityRead } from './communityRead';

export interface MyCommunities {
  owned?: CommunityRead[];
  joined?: CommunityRead[];
  pending?: CommunityRead[];
}
