/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { PlanReadRouteGeometry } from './planReadRouteGeometry';
import type { PlanReportRead } from './planReportRead';

export interface PlanRead {
  id: string;
  user_id: string;
  name?: string | null;
  start_latitude: number;
  start_longitude: number;
  status: string;
  total_distance_meters?: number | null;
  total_duration_seconds?: number | null;
  route_geometry?: PlanReadRouteGeometry;
  google_maps_url?: string | null;
  created_at: string;
  updated_at?: string | null;
  plan_reports?: PlanReportRead[];
}
