/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface PlanListRead {
  id: string;
  name?: string | null;
  start_latitude: number;
  start_longitude: number;
  status: string;
  total_distance_meters?: number | null;
  total_duration_seconds?: number | null;
  report_count: number;
  created_at: string;
}
