/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { BinRead } from './binRead';

export interface PlanBinRead {
  id: string;
  bin_id: string;
  visit_order: number;
  leg_distance_meters?: number | null;
  leg_duration_seconds?: number | null;
  bin: BinRead;
}
