/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface PostRead {
  id: string;
  community_id: string;
  content: string;
  created_at: string;
}
