/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface ProfileUpdate {
  full_name?: string | null;
  avatar_url?: string | null;
  city_latitude?: number | null;
  city_longitude?: number | null;
}
