/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { BadgeRead } from './badgeRead';

export interface PublicProfile {
  name: string;
  avatar_url?: string | null;
  badges?: BadgeRead[];
  member_since: string;
}
