/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

/**
 * Admin-only winner detail with full contact info.
 */
export interface RaffleWinnerContact {
  prize_id: string;
  prize_title: string;
  prize_position: number;
  user_id: string;
  full_name: string;
  email: string;
}
