/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { RafflePrizeRead } from './rafflePrizeRead';

export interface RaffleRead {
  id: string;
  title: string;
  description: string;
  end_date: string;
  created_by?: string | null;
  drawn_at?: string | null;
  prizes?: RafflePrizeRead[];
  created_at: string;
  updated_at?: string | null;
}
