/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface ReportStatusLogRead {
  id: string;
  action: string;
  cycle: number;
  performed_by_user_id?: string | null;
  created_at: string;
}
