/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface ReportUpdate {
  description?: string | null;
  report_type?: string | null;
  what3words?: string | null;
  remove_image_ids?: string[] | null;
}
