/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import type { ReportImageRead } from './reportImageRead';

export interface ReportRead {
  id: number;
  latitude: number;
  longitude: number;
  description: string;
  what3words?: string | null;
  created_by_user_id?: number | null;
  resolved_by_user_id?: number | null;
  resolved_at?: string | null;
  status: string;
  created_at: string;
  images?: ReportImageRead[];
}
