/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { ReportImageRead } from './reportImageRead';

export interface ReportRead {
  id: string;
  latitude: number;
  longitude: number;
  report_type: string;
  description: string;
  what3words?: string | null;
  address?: string | null;
  created_by_user_id?: string | null;
  resolved_by_user_id?: string | null;
  resolved_at?: string | null;
  status: string;
  created_at: string;
  images?: ReportImageRead[];
}
