/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface ReportCommentRead {
  id: string;
  report_id: string;
  user_id: string;
  body: string;
  created_at: string;
}
