/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */

export interface ReportRead {
  latitude: number;
  longitude: number;
  description?: string;
  photo_url?: string | null;
  id: number;
  status: string;
  created_at: string;
}
