/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */

export interface UserCreate {
  email: string;
  full_name: string;
  password: string;
  city_latitude: number;
  city_longitude: number;
}
