/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */

export interface UserRead {
  id: number;
  email: string;
  full_name: string;
  user_type: string;
  created_at: string;
}
