/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type { BadgeRead } from './badgeRead';

export interface UserRead {
  id: string;
  email: string;
  full_name: string;
  is_verified: boolean;
  user_type: string;
  avatar_url?: string | null;
  city_latitude: number;
  city_longitude: number;
  created_at: string;
  badges?: BadgeRead[];
  linked_providers?: string[];
  has_password?: boolean;
}
