"""add what3words to reports

Revision ID: 336a384b8798
Revises: b5c96d033e62
Create Date: 2026-03-13 15:27:25.652564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "336a384b8798"
down_revision: Union[str, None] = "b5c96d033e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("what3words", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "what3words")
    # ### end Alembic commands ###
