"""add communities feature

Revision ID: 3a9e288db961
Revises: 3b1048682efd
Create Date: 2026-03-26 21:44:55.907252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a9e288db961"
down_revision: Union[str, None] = "3b1048682efd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("facebook_url", sa.String(), nullable=True),
        sa.Column("profile_image", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("radius_km", sa.Float(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "under_review", name="communitystatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_communities_id"), "communities", ["id"], unique=False)
    op.create_index(op.f("ix_communities_owner_id"), "communities", ["owner_id"], unique=False)
    op.create_table(
        "community_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("meeting_latitude", sa.Float(), nullable=False),
        sa.Column("meeting_longitude", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_events_community_id"), "community_events", ["community_id"], unique=False
    )
    op.create_index(op.f("ix_community_events_id"), "community_events", ["id"], unique=False)
    op.create_table(
        "community_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="membershipstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "user_id", name="uq_community_user"),
    )
    op.create_index(
        op.f("ix_community_memberships_community_id"),
        "community_memberships",
        ["community_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_memberships_id"), "community_memberships", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_community_memberships_user_id"), "community_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "community_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_posts_community_id"), "community_posts", ["community_id"], unique=False
    )
    op.create_index(op.f("ix_community_posts_id"), "community_posts", ["id"], unique=False)
    op.create_table(
        "event_reports",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["community_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "report_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_reports")
    op.drop_index(op.f("ix_community_posts_id"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_community_id"), table_name="community_posts")
    op.drop_table("community_posts")
    op.drop_index(op.f("ix_community_memberships_user_id"), table_name="community_memberships")
    op.drop_index(op.f("ix_community_memberships_id"), table_name="community_memberships")
    op.drop_index(op.f("ix_community_memberships_community_id"), table_name="community_memberships")
    op.drop_table("community_memberships")
    op.drop_index(op.f("ix_community_events_id"), table_name="community_events")
    op.drop_index(op.f("ix_community_events_community_id"), table_name="community_events")
    op.drop_table("community_events")
    op.drop_index(op.f("ix_communities_owner_id"), table_name="communities")
    op.drop_index(op.f("ix_communities_id"), table_name="communities")
    op.drop_table("communities")
    # ### end Alembic commands ###
