"""add thumbnail_url to report_images

Revision ID: 69e943d78e72
Revises: 6d0d5c38624b
Create Date: 2026-03-15 09:03:09.331206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69e943d78e72"
down_revision: Union[str, None] = "6d0d5c38624b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report_images", sa.Column("thumbnail_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_images", "thumbnail_url")
    # ### end Alembic commands ###
