"""add_users_table_and_report_images

Revision ID: 6d0d5c38624b
Revises: 336a384b8798
Create Date: 2026-03-13 21:50:48.888780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0d5c38624b'
down_revision: Union[str, None] = '336a384b8798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('user_type', sa.Enum('superuser', 'admin', 'moderator', 'volunteer', name='usertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('report_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('image_type', sa.Enum('report', 'resolved', name='imagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_images_id'), 'report_images', ['id'], unique=False)
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    with op.batch_alter_table('reports') as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_reports_created_by_user_id', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_reports_resolved_by_user_id', 'users', ['resolved_by_user_id'], ['id'])
        batch_op.drop_column('photo_url')


def downgrade() -> None:
    with op.batch_alter_table('reports') as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_reports_created_by_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reports_resolved_by_user_id', type_='foreignkey')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolved_by_user_id')
        batch_op.drop_column('created_by_user_id')
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.drop_index(op.f('ix_report_images_id'), table_name='report_images')
    op.drop_table('report_images')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
