"""add address to reports

Revision ID: e44cc152ac4d
Revises: 0445d97d2ec1
Create Date: 2026-03-22 20:31:07.477603

"""

import sys
import time
from typing import Sequence, Union

import httpx
from alembic import op
import sqlalchemy as sa


def _log(msg: str) -> None:
    print(msg, flush=True)


# revision identifiers, used by Alembic.
revision: str = "e44cc152ac4d"
down_revision: Union[str, None] = "0445d97d2ec1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _reverse_geocode(lat: float, lon: float) -> str | None:
    """Reverse geocode with retry on 429."""
    for attempt in range(5):
        try:
            _log(f"    Requesting geocode for ({lat}, {lon}) attempt {attempt + 1}/5...")
            resp = httpx.get(
                "https://nominatim.openstreetmap.org/reverse",
                params={"lat": lat, "lon": lon, "format": "json", "addressdetails": "1"},
                headers={"User-Agent": "MapTheMess/1.0", "Accept-Language": "en"},
                timeout=10,
            )
            _log(f"    Response status: {resp.status_code}")
            if resp.status_code == 429:
                wait = 2**attempt
                _log(f"    Rate limited (429), waiting {wait}s before retry...")
                time.sleep(wait)
                continue
            if resp.status_code != 200:
                _log(f"    Unexpected status {resp.status_code}, skipping")
                return None
            addr = resp.json().get("address", {})
            parts = [
                addr.get("road") or addr.get("pedestrian") or addr.get("footway") or "",
                addr.get("city")
                or addr.get("town")
                or addr.get("village")
                or addr.get("hamlet")
                or "",
                addr.get("postcode") or "",
            ]
            display = ", ".join(p for p in parts if p)
            return display or None
        except Exception as e:
            _log(f"    Error: {e}, retrying in 2s...")
            time.sleep(2)
    _log("    All attempts failed, skipping")
    return None


def _backfill_addresses(connection: sa.Connection) -> None:
    """Backfill addresses for all existing reports, 1 per second."""
    reports_table = sa.table(
        "reports",
        sa.column("id", sa.Integer),
        sa.column("latitude", sa.Float),
        sa.column("longitude", sa.Float),
        sa.column("address", sa.String),
    )
    rows = connection.execute(
        sa.select(reports_table.c.id, reports_table.c.latitude, reports_table.c.longitude).where(
            reports_table.c.address.is_(None)
        )
    ).fetchall()

    total = len(rows)
    if total == 0:
        _log("No reports to backfill.")
        return

    _log(f"Backfilling addresses for {total} reports...")
    for i, (report_id, lat, lon) in enumerate(rows, 1):
        _log(f"  [{i}/{total}] Report #{report_id} ({lat}, {lon})")
        address = _reverse_geocode(lat, lon)
        if address:
            connection.execute(
                reports_table.update()
                .where(reports_table.c.id == report_id)
                .values(address=address)
            )
            _log(f"  [{i}/{total}] Report #{report_id} -> {address}")
        else:
            _log(f"  [{i}/{total}] Report #{report_id} -> no address, skipped")
        if i < total:
            _log(f"  Waiting 1s before next request...")
            time.sleep(1)

    _log("Backfill complete.")


def upgrade() -> None:
    op.add_column("reports", sa.Column("address", sa.String(), nullable=True))
    # Backfill existing reports
    connection = op.get_bind()
    _backfill_addresses(connection)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "address")
    # ### end Alembic commands ###
