"""add favourites table

Revision ID: ea2fec8170bc
Revises: 69e943d78e72
Create Date: 2026-03-18 16:12:46.957844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ea2fec8170bc"
down_revision: Union[str, None] = "69e943d78e72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "report_id", name="uq_user_report"),
    )
    op.create_index(op.f("ix_favourites_id"), "favourites", ["id"], unique=False)
    op.create_index(op.f("ix_favourites_report_id"), "favourites", ["report_id"], unique=False)
    op.create_index(op.f("ix_favourites_user_id"), "favourites", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favourites_user_id"), table_name="favourites")
    op.drop_index(op.f("ix_favourites_report_id"), table_name="favourites")
    op.drop_index(op.f("ix_favourites_id"), table_name="favourites")
    op.drop_table("favourites")
    # ### end Alembic commands ###
