"""add community_memberships table

Revision ID: f5aa4f555429
Revises: 5a2cba4dd38c
Create Date: 2026-03-25 21:41:58.376003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f5aa4f555429"
down_revision: Union[str, None] = "5a2cba4dd38c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="membershipstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "user_id", name="uq_community_user"),
    )
    op.create_index(
        op.f("ix_community_memberships_community_id"),
        "community_memberships",
        ["community_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_memberships_id"), "community_memberships", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_community_memberships_user_id"), "community_memberships", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_community_memberships_user_id"), table_name="community_memberships")
    op.drop_index(op.f("ix_community_memberships_id"), table_name="community_memberships")
    op.drop_index(op.f("ix_community_memberships_community_id"), table_name="community_memberships")
    op.drop_table("community_memberships")
    # ### end Alembic commands ###
