/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: dev
 */
import type {
  BinCreate,
  BinRead,
  BinUpdate,
  ListBinsApiBinsGetParams
} from '../../model';

import { customInstance } from '../../client';



  export const getBins = () => {
/**
 * List bins, optionally filtered to those within ``radius_km`` of (latitude, longitude).

The map only shows bins at high zoom, so the default radius is small (1 km).
 * @summary List Bins
 */
const listBinsApiBinsGet = (
    params?: ListBinsApiBinsGetParams,
 ) => {
      return customInstance<BinRead[]>(
      {url: `/api/bins/`, method: 'GET',
        params
    },
      );
    }
  /**
 * Create a new bin location. Requires authentication.
 * @summary Create Bin
 */
const createBinApiBinsPost = (
    binCreate: BinCreate,
 ) => {
      return customInstance<BinRead>(
      {url: `/api/bins/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: binCreate
    },
      );
    }
  /**
 * @summary Get Bin
 */
const getBinApiBinsBinIdGet = (
    binId: string,
 ) => {
      return customInstance<BinRead>(
      {url: `/api/bins/${binId}`, method: 'GET'
    },
      );
    }
  /**
 * Edit a bin. Allowed for the owner, moderator, admin, or superuser.
 * @summary Update Bin
 */
const updateBinApiBinsBinIdPatch = (
    binId: string,
    binUpdate: BinUpdate,
 ) => {
      return customInstance<BinRead>(
      {url: `/api/bins/${binId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: binUpdate
    },
      );
    }
  /**
 * Delete a bin. Allowed for the owner, moderator, admin, or superuser.
 * @summary Delete Bin
 */
const deleteBinApiBinsBinIdDelete = (
    binId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/bins/${binId}`, method: 'DELETE'
    },
      );
    }
  return {listBinsApiBinsGet,createBinApiBinsPost,getBinApiBinsBinIdGet,updateBinApiBinsBinIdPatch,deleteBinApiBinsBinIdDelete}};
export type ListBinsApiBinsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBins>['listBinsApiBinsGet']>>>
export type CreateBinApiBinsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBins>['createBinApiBinsPost']>>>
export type GetBinApiBinsBinIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBins>['getBinApiBinsBinIdGet']>>>
export type UpdateBinApiBinsBinIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBins>['updateBinApiBinsBinIdPatch']>>>
export type DeleteBinApiBinsBinIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBins>['deleteBinApiBinsBinIdDelete']>>>
