/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyAddImageApiReportsReportIdImagesPost,
  BodyCreateReportApiReportsPost,
  ListReportsApiReportsGetParams,
  ReportImageRead,
  ReportRead
} from '../../model';




  export const getReports = (axiosInstance: AxiosInstance = axios) => {
/**
 * Serve an uploaded image by filename.
 * @summary Serve Image
 */
const serveImageApiReportsImagesFilenameGet = (
    filename: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/api/reports/images/${filename}`,options
    );
  }
/**
 * List all reports, optionally filtered by status.
 * @summary List Reports
 */
const listReportsApiReportsGet = (
    params?: ListReportsApiReportsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead[]>> => {
    return axiosInstance.get(
      `/api/reports/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new litter report with optional image uploads.
 * @summary Create Report
 */
const createReportApiReportsPost = (
    bodyCreateReportApiReportsPost: BodyCreateReportApiReportsPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {const formData = new FormData();
formData.append(`latitude`, bodyCreateReportApiReportsPost.latitude.toString())
formData.append(`longitude`, bodyCreateReportApiReportsPost.longitude.toString())
if(bodyCreateReportApiReportsPost.description !== undefined) {
 formData.append(`description`, bodyCreateReportApiReportsPost.description);
 }
if(bodyCreateReportApiReportsPost.what3words !== undefined && bodyCreateReportApiReportsPost.what3words !== null) {
 formData.append(`what3words`, bodyCreateReportApiReportsPost.what3words);
 }
if(bodyCreateReportApiReportsPost.images !== undefined) {
 bodyCreateReportApiReportsPost.images.forEach(value => formData.append(`images`, value));
 }

    return axiosInstance.post(
      `/api/reports/`,
      formData,options
    );
  }
/**
 * @summary Get Report
 */
const getReportApiReportsReportIdGet = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.get(
      `/api/reports/${reportId}`,options
    );
  }
/**
 * Delete a report. Requires moderator or admin role.
 * @summary Delete Report
 */
const deleteReportApiReportsReportIdDelete = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/reports/${reportId}`,options
    );
  }
/**
 * Upload an image and attach it to an existing report.
 * @summary Add Image
 */
const addImageApiReportsReportIdImagesPost = (
    reportId: number,
    bodyAddImageApiReportsReportIdImagesPost: BodyAddImageApiReportsReportIdImagesPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportImageRead>> => {const formData = new FormData();
formData.append(`image_type`, bodyAddImageApiReportsReportIdImagesPost.image_type);
formData.append(`file`, bodyAddImageApiReportsReportIdImagesPost.file);

    return axiosInstance.post(
      `/api/reports/${reportId}/images`,
      formData,options
    );
  }
/**
 * Mark a report as cleaned. Attaches the user id if authenticated.
 * @summary Mark Cleaned
 */
const markCleanedApiReportsReportIdCleanPatch = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.patch(
      `/api/reports/${reportId}/clean`,undefined,options
    );
  }
/**
 * Set a report back to pending. Requires moderator or admin role.
 * @summary Mark Unresolved
 */
const markUnresolvedApiReportsReportIdUnresolvePatch = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.patch(
      `/api/reports/${reportId}/unresolve`,undefined,options
    );
  }
return {serveImageApiReportsImagesFilenameGet,listReportsApiReportsGet,createReportApiReportsPost,getReportApiReportsReportIdGet,deleteReportApiReportsReportIdDelete,addImageApiReportsReportIdImagesPost,markCleanedApiReportsReportIdCleanPatch,markUnresolvedApiReportsReportIdUnresolvePatch}};
export type ServeImageApiReportsImagesFilenameGetResult = AxiosResponse<unknown>
export type ListReportsApiReportsGetResult = AxiosResponse<ReportRead[]>
export type CreateReportApiReportsPostResult = AxiosResponse<ReportRead>
export type GetReportApiReportsReportIdGetResult = AxiosResponse<ReportRead>
export type DeleteReportApiReportsReportIdDeleteResult = AxiosResponse<void>
export type AddImageApiReportsReportIdImagesPostResult = AxiosResponse<ReportImageRead>
export type MarkCleanedApiReportsReportIdCleanPatchResult = AxiosResponse<ReportRead>
export type MarkUnresolvedApiReportsReportIdUnresolvePatchResult = AxiosResponse<ReportRead>
