/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ListReportsApiReportsGetParams,
  ReportCreate,
  ReportRead
} from '../../model';




  export const getReports = (axiosInstance: AxiosInstance = axios) => {
/**
 * List all reports, optionally filtered by status.
 * @summary List Reports
 */
const listReportsApiReportsGet = (
    params?: ListReportsApiReportsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead[]>> => {
    return axiosInstance.get(
      `/api/reports/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new litter report.
 * @summary Create Report
 */
const createReportApiReportsPost = (
    reportCreate: ReportCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.post(
      `/api/reports/`,
      reportCreate,options
    );
  }
/**
 * @summary Get Report
 */
const getReportApiReportsReportIdGet = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.get(
      `/api/reports/${reportId}`,options
    );
  }
/**
 * Mark a report as cleaned.
 * @summary Mark Cleaned
 */
const markCleanedApiReportsReportIdCleanPatch = (
    reportId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReportRead>> => {
    return axiosInstance.patch(
      `/api/reports/${reportId}/clean`,undefined,options
    );
  }
return {listReportsApiReportsGet,createReportApiReportsPost,getReportApiReportsReportIdGet,markCleanedApiReportsReportIdCleanPatch}};
export type ListReportsApiReportsGetResult = AxiosResponse<ReportRead[]>
export type CreateReportApiReportsPostResult = AxiosResponse<ReportRead>
export type GetReportApiReportsReportIdGetResult = AxiosResponse<ReportRead>
export type MarkCleanedApiReportsReportIdCleanPatchResult = AxiosResponse<ReportRead>
