/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import type {
  BodyAddImageApiReportsReportIdImagesPost,
  BodyCreateReportApiReportsPost,
  ListReportsApiReportsGetParams,
  ReportImageRead,
  ReportRead
} from '../../model';

import { customInstance } from '../../client';



  export const getReports = () => {
/**
 * Serve an uploaded image by filename.
 * @summary Serve Image
 */
const serveImageApiReportsImagesFilenameGet = (
    filename: string,
 ) => {
      return customInstance<unknown>(
      {url: `/api/reports/images/${filename}`, method: 'GET'
    },
      );
    }
  /**
 * List all reports, optionally filtered by status.
 * @summary List Reports
 */
const listReportsApiReportsGet = (
    params?: ListReportsApiReportsGetParams,
 ) => {
      return customInstance<ReportRead[]>(
      {url: `/api/reports/`, method: 'GET',
        params
    },
      );
    }
  /**
 * Create a new litter report with optional image uploads.
 * @summary Create Report
 */
const createReportApiReportsPost = (
    bodyCreateReportApiReportsPost: BodyCreateReportApiReportsPost,
 ) => {const formData = new FormData();
formData.append(`latitude`, bodyCreateReportApiReportsPost.latitude.toString())
formData.append(`longitude`, bodyCreateReportApiReportsPost.longitude.toString())
if(bodyCreateReportApiReportsPost.description !== undefined) {
 formData.append(`description`, bodyCreateReportApiReportsPost.description);
 }
if(bodyCreateReportApiReportsPost.what3words !== undefined && bodyCreateReportApiReportsPost.what3words !== null) {
 formData.append(`what3words`, bodyCreateReportApiReportsPost.what3words);
 }
if(bodyCreateReportApiReportsPost.images !== undefined) {
 bodyCreateReportApiReportsPost.images.forEach(value => formData.append(`images`, value));
 }

      return customInstance<ReportRead>(
      {url: `/api/reports/`, method: 'POST',
       data: formData
    },
      );
    }
  /**
 * @summary Get Report
 */
const getReportApiReportsReportIdGet = (
    reportId: number,
 ) => {
      return customInstance<ReportRead>(
      {url: `/api/reports/${reportId}`, method: 'GET'
    },
      );
    }
  /**
 * Delete a report. Requires moderator or admin role.
 * @summary Delete Report
 */
const deleteReportApiReportsReportIdDelete = (
    reportId: number,
 ) => {
      return customInstance<void>(
      {url: `/api/reports/${reportId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Upload an image and attach it to an existing report.
 * @summary Add Image
 */
const addImageApiReportsReportIdImagesPost = (
    reportId: number,
    bodyAddImageApiReportsReportIdImagesPost: BodyAddImageApiReportsReportIdImagesPost,
 ) => {const formData = new FormData();
formData.append(`image_type`, bodyAddImageApiReportsReportIdImagesPost.image_type);
formData.append(`file`, bodyAddImageApiReportsReportIdImagesPost.file);

      return customInstance<ReportImageRead>(
      {url: `/api/reports/${reportId}/images`, method: 'POST',
       data: formData
    },
      );
    }
  /**
 * Mark a report as cleaned. Attaches the user id if authenticated.
 * @summary Mark Cleaned
 */
const markCleanedApiReportsReportIdCleanPatch = (
    reportId: number,
 ) => {
      return customInstance<ReportRead>(
      {url: `/api/reports/${reportId}/clean`, method: 'PATCH'
    },
      );
    }
  /**
 * Set a report back to pending. Requires moderator or admin role.
 * @summary Mark Unresolved
 */
const markUnresolvedApiReportsReportIdUnresolvePatch = (
    reportId: number,
 ) => {
      return customInstance<ReportRead>(
      {url: `/api/reports/${reportId}/unresolve`, method: 'PATCH'
    },
      );
    }
  return {serveImageApiReportsImagesFilenameGet,listReportsApiReportsGet,createReportApiReportsPost,getReportApiReportsReportIdGet,deleteReportApiReportsReportIdDelete,addImageApiReportsReportIdImagesPost,markCleanedApiReportsReportIdCleanPatch,markUnresolvedApiReportsReportIdUnresolvePatch}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ServeImageApiReportsImagesFilenameGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['serveImageApiReportsImagesFilenameGet']>>>
export type ListReportsApiReportsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['listReportsApiReportsGet']>>>
export type CreateReportApiReportsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['createReportApiReportsPost']>>>
export type GetReportApiReportsReportIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['getReportApiReportsReportIdGet']>>>
export type DeleteReportApiReportsReportIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['deleteReportApiReportsReportIdDelete']>>>
export type AddImageApiReportsReportIdImagesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['addImageApiReportsReportIdImagesPost']>>>
export type MarkCleanedApiReportsReportIdCleanPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['markCleanedApiReportsReportIdCleanPatch']>>>
export type MarkUnresolvedApiReportsReportIdUnresolvePatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['markUnresolvedApiReportsReportIdUnresolvePatch']>>>
