/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Map the Mess API
 * Backend for the community litter reporting platform
 * OpenAPI spec version: 0.1.0
 */
import { customInstance } from '../../client';



  export const getDefault = () => {
/**
 * @summary Root
 */
const rootGet = (
    
 ) => {
      return customInstance<unknown>(
      {url: `/`, method: 'GET'
    },
      );
    }
  return {}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

